name: Publish mixed mode results to step summary

runs:
  using: "composite"
  steps:
  - name: Generate markdown
    shell: bash
    run: python3 build/publish-mixed-mode-results.py --results-path "mixed-mode-*-test-reports/overall.txt" --output mixed-mode-results.md $(python build/versionutils.py gradle.properties)
  - name: Preview mixed-mode results
    shell: bash
    run: cat mixed-mode-results.md >> $GITHUB_STEP_SUMMARY
