changelog:
  # TODO exclude commits from release process
  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"
    - title: New Features
      labels:
        - enhancement
    - title: Documentation improvements
      labels:
        - documentation
    - title: Bug Fixes
      labels:
        - "bug fix"
    - title: Performance Improvements
      labels:
        - performance
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
