changelog:
  # TODO exclude commits from release process
  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - "bug fix"
    - title: Performance Improvements
      labels:
        - performance
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Build/Test/Documentation Improvements
      labels:
        - "build improvement"
        - "documentation"
        - "testing improvement"
    - title: Other Changes
      labels:
        - "*"
