name: Documentation Build And Publish

inputs:
  artifact_version:
    description: 'Target version of final artifacts'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Build site
      uses: ./actions/gradle-build
      with:
        artifact_version: ${{ inputs.artifact_version }}
        gradle_command: "documentationSite"
    - name: Upload site artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/sphinx/.out/html/
    - name: Deploy site to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
