name: Gradle Test

inputs:
  fdb_version:
    description: 'Version of FDB to run'
    required: false
    default: "7.3.42"
  gradle_command:
    description: 'Gradle command to run'
    default: build destructiveTest
    required: false
  gradle_args:
    description: 'Gradle arguments for running'
    required: true
  report_name:
    description: 'Test report artifact name'
    required: false
    default: "test-reports"

runs:
  using: "composite"
  steps:
  - name: Run build and test
    uses: ./actions/run-gradle
    with:
      gradle_command: ${{ inputs.gradle_command }} -PcoreNotStrict -Ptests.ci=true ${{ inputs.gradle_args }}
  - name: Test Summary
    shell: bash
    if: ${{ !cancelled() && hashFiles('.out/reports/test-summary.md') != '' }}
    run: cat .out/reports/test-summary.md > $GITHUB_STEP_SUMMARY
  - name: Test Failures
    shell: bash
    if: ${{ !cancelled() && hashFiles('.out/reports/test-failures.md') != '' }}
    run: cat .out/reports/test-failures.md > $GITHUB_STEP_SUMMARY
  - name: Copy Test Reports
    shell: bash
    if: ${{ !cancelled() }}
    run: |
       mkdir -p test-reports
       for d in fdb-java-annotations fdb-extensions fdb-test-utils fdb-record-layer-core fdb-record-layer-icu fdb-record-layer-spatial fdb-record-layer-lucene fdb-record-layer-jmh examples fdb-relational-api fdb-relational-core fdb-relational-cli fdb-relational-grpc fdb-relational-jdbc fdb-relational-server yaml-tests; do
         if [[ -d "$d/.out/reports" ]] ; then
           ln -s "../$d/.out/reports" "test-reports/$d"
         fi
       done
  - name: Overall failure
    if: ${{ failure() }}
    shell: bash
    run: |
      echo "FAILURE" >> test-reports/overall.txt
  - name: Overall success
    if: ${{ success() }}
    shell: bash
    run: |
      echo "SUCCESS" >> test-reports/overall.txt
  - name: Publish Test Reports
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@v4.6.0
    with:
      name: ${{ inputs.report_name }}
      if-no-files-found: ignore
      path: |
            test-reports/fdb-java-annotations/
            test-reports/fdb-extensions/
            test-reports/fdb-test-utils/
            test-reports/fdb-record-layer-core/
            test-reports/fdb-record-layer-icu/
            test-reports/fdb-record-layer-spatial/
            test-reports/fdb-record-layer-lucene/
            test-reports/fdb-record-layer-jmh/
            test-reports/examples/
            test-reports/fdb-relational-api/
            test-reports/fdb-relational-core/
            test-reports/fdb-relational-cli/
            test-reports/fdb-relational-grpc/
            test-reports/fdb-relational-jdbc/
            test-reports/fdb-relational-server/
            test-reports/yaml-tests/
            test-reports/overall.txt
