name: Gradle Test

inputs:
  fdb_version:
    description: 'Version of FDB to run'
    required: false
    default: "7.3.42"
  gradle_command:
    description: 'Gradle command to run'
    default: build destructiveTest
    required: false
  gradle_args:
    description: 'Gradle arguments for running'
    required: true

runs:
  using: "composite"
  steps:
  - name: Run build and test
    uses: ./actions/run-gradle
    with:
      gradle_command: ${{ inputs.gradle_command }} -PcoreNotStrict -Ptests.ci=true ${{ inputs.gradle_args }}
  - name: Test Summary
    shell: bash
    if: ${{ !cancelled() && hashFiles('.out/reports/test-summary.md') != '' }}
    run: cat .out/reports/test-summary.md > $GITHUB_STEP_SUMMARY
  - name: Test Failures
    shell: bash
    if: ${{ !cancelled() && hashFiles('.out/reports/test-failures.md') != '' }}
    run: cat .out/reports/test-failures.md > $GITHUB_STEP_SUMMARY
  - name: Copy Test Reports
    shell: bash
    if: always()
    run: mkdir -p test-reports && for d in fdb-java-annotations fdb-extensions fdb-test-utils fdb-record-layer-core fdb-record-layer-icu fdb-record-layer-spatial fdb-record-layer-lucene fdb-record-layer-jmh examples fdb-relational-api fdb-relational-core fdb-relational-cli fdb-relational-grpc fdb-relational-jdbc fdb-relational-server yaml-tests; do ln -s ../$d/.out/reports test-reports/$d; done
