/*
 * QueryPredicateSimplificationRuleCall.java
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2015-2025 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.apple.foundationdb.record.query.plan.cascades.predicates.simplification;

import com.apple.foundationdb.annotation.API;
import com.apple.foundationdb.record.EvaluationContext;
import com.apple.foundationdb.record.query.plan.QueryPlanConstraint;
import com.apple.foundationdb.record.query.plan.cascades.AliasMap;
import com.apple.foundationdb.record.query.plan.cascades.CorrelationIdentifier;
import com.apple.foundationdb.record.query.plan.cascades.PlannerRule;
import com.apple.foundationdb.record.query.plan.cascades.PlannerRuleCall;
import com.apple.foundationdb.record.query.plan.cascades.matching.structure.PlannerBindings;
import com.apple.foundationdb.record.query.plan.cascades.predicates.QueryPredicate;

import javax.annotation.Nonnull;
import java.util.Set;
import java.util.function.Function;

/**
 * A rule call implementation for the simplification of {@link QueryPredicate} trees. This rule call implements the
 * logic for handling new {@link QueryPredicate}s as they are generated by a {@link com.apple.foundationdb.record.query.plan.cascades.predicates.simplification.AbstractQueryPredicateRule#onMatch(PlannerRuleCall)} and
 * passed to the rule call via the yield method.
 */
@API(API.Status.EXPERIMENTAL)
public class QueryPredicateSimplificationRuleCall extends AbstractQueryPredicateRuleCall<QueryPredicate, QueryPredicateSimplificationRuleCall> {

    public QueryPredicateSimplificationRuleCall(@Nonnull final PlannerRule<QueryPredicateSimplificationRuleCall, ? extends QueryPredicate> rule,
                                                @Nonnull final QueryPredicate root,
                                                @Nonnull final QueryPredicate current,
                                                @Nonnull final EvaluationContext evaluationContext,
                                                @Nonnull final PlannerBindings bindings,
                                                @Nonnull final AliasMap aliasMap,
                                                @Nonnull final Set<CorrelationIdentifier> constantAliases,
                                                @Nonnull final Function<QueryPredicate, QueryPlanConstraint> retrieveQueryPlanConstraintFunction) {
        super(rule, root, current, evaluationContext, bindings, aliasMap, constantAliases,
                retrieveQueryPlanConstraintFunction);
    }
}
