/*
 * IndexEntryTranslatorEquivalenceTest.java
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2015-2026 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.apple.foundationdb.record.query.plan.cascades;

import com.apple.foundationdb.record.Bindings;
import com.apple.foundationdb.record.EvaluationContext;
import com.apple.foundationdb.record.IndexEntry;
import com.apple.foundationdb.record.RecordMetaData;
import com.apple.foundationdb.record.TestRecords1Proto;
import com.apple.foundationdb.record.TestRecordsWithHeaderProto;
import com.apple.foundationdb.record.metadata.Index;
import com.apple.foundationdb.record.query.plan.cascades.typing.Type;
import com.apple.foundationdb.record.query.plan.cascades.typing.TypeRepository;
import com.apple.foundationdb.record.query.plan.cascades.values.FieldValue;
import com.apple.foundationdb.record.query.plan.cascades.values.QuantifiedObjectValue;
import com.apple.foundationdb.record.query.plan.cascades.values.RecordConstructorValue;
import com.apple.foundationdb.record.query.plan.cascades.values.Value;
import com.apple.foundationdb.tuple.Tuple;
import com.apple.foundationdb.tuple.TupleHelpers;
import com.google.common.collect.ImmutableList;
import com.google.protobuf.Descriptors;
import com.google.protobuf.Message;
import org.junit.jupiter.api.Test;

import javax.annotation.Nonnull;
import java.util.List;

import static com.apple.foundationdb.record.metadata.Key.Expressions.concat;
import static com.apple.foundationdb.record.metadata.Key.Expressions.concatenateFields;
import static com.apple.foundationdb.record.metadata.Key.Expressions.field;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * The two index entry translators of a covering scan -- the copiers of an {@code IndexKeyValueToPartialRecord} and the
 * value that reads the entry directly -- are derived from the same call and decode an entry into the same record.
 */
class IndexEntryTranslatorEquivalenceTest {

    /**
     * An index whose columns sit at two levels of the record, and whose primary key sits inside a nested message, as
     * {@code FDBCoveringIndexQueryTest} defines it over {@code MyRecord}:
     * <pre>
     *   primary key : header.rec_no
     *   index multi : str_value, header.path, header.num
     *   entry key   : ( "abc", "/a", 1, 7 )   with the primary key appended
     *   record      : MyRecord { str_value: "abc", header: { path: "/a", num: 1, rec_no: 7 } }
     * </pre>
     * Both translators are generated by the one call to
     * {@link ScanWithFetchMatchCandidate#computeIndexEntryToLogicalRecord}, so this covers how each is derived and not
     * only how each behaves.
     */
    @Test
    void bothTranslatorsDecodeANestedEntryAlike() {
        final var metaDataBuilder = RecordMetaData.newBuilder()
                .setRecords(TestRecordsWithHeaderProto.getDescriptor());
        metaDataBuilder.getRecordType("MyRecord").setPrimaryKey(field("header").nest(field("rec_no")));
        metaDataBuilder.addIndex("MyRecord", new Index("multi",
                concat(field("str_value"), field("header").nest(concatenateFields("path", "num")))));
        final var recordType = metaDataBuilder.build().getRecordType("MyRecord");
        final var descriptor = recordType.getDescriptor();
        final var baseType = Type.Record.fromDescriptor(descriptor);
        final var baseAlias = Quantifier.current();
        final var baseObjectValue = QuantifiedObjectValue.of(baseAlias, baseType);

        // One value per entry key column, as the index expansion produces them: the index's own columns followed by the
        // primary key, which here lives inside the nested message.
        final var indexKeyValues = ImmutableList.<Value>of(
                FieldValue.ofFieldNames(baseObjectValue, List.of("str_value")),
                FieldValue.ofFieldNames(baseObjectValue, List.of("header", "path")),
                FieldValue.ofFieldNames(baseObjectValue, List.of("header", "num")),
                FieldValue.ofFieldNames(baseObjectValue, List.of("header", "rec_no")));

        final var translators = ScanWithFetchMatchCandidate.computeIndexEntryToLogicalRecord(List.of(recordType),
                baseAlias, baseType, indexKeyValues, ImmutableList.of()).orElseThrow();
        final var copiers = translators.indexKeyValueToPartialRecord();
        final var recordValue = translators.indexEntryToRecordValue();
        assertNotNull(recordValue, "a nested index should still yield a value based translator");

        final var entry = new IndexEntry(metaDataBuilder.build().getIndex("multi"),
                Tuple.from("abc", "/a", 1L, 7L), TupleHelpers.EMPTY);

        final var byCopiers = copiers.toRecord(descriptor, entry);
        final var byValue = evaluate(recordValue, entry);

        // Non-vacuous: both really carry all four columns, three of them inside the nested message.
        assertEquals("abc", byCopiers.getField(descriptor.findFieldByName("str_value")));
        final var header = (Message)byCopiers.getField(descriptor.findFieldByName("header"));
        final var headerDescriptor = descriptor.findFieldByName("header").getMessageType();
        assertEquals("/a", header.getField(headerDescriptor.findFieldByName("path")));
        assertEquals(1, header.getField(headerDescriptor.findFieldByName("num")));
        assertEquals(7L, header.getField(headerDescriptor.findFieldByName("rec_no")));

        assertSameRecord(descriptor, byCopiers, byValue);
    }

    /**
     * An index may carry the same field twice, as {@code concat(num_value_2, num_value_2)} does, so the entry holds it at
     * two positions. Either reconstructs it identically, so each translator keeps a single column, reading the first.
     */
    @Test
    void bothTranslatorsKeepTheFirstColumnOfARepeatedField() {
        final var metaDataBuilder = RecordMetaData.newBuilder().setRecords(TestRecords1Proto.getDescriptor());
        metaDataBuilder.addIndex("MySimpleRecord", new Index("dup",
                concat(field("num_value_2"), field("num_value_2"))));
        final var metaData = metaDataBuilder.build();
        final var recordType = metaData.getRecordType("MySimpleRecord");
        final var descriptor = recordType.getDescriptor();
        final var baseType = Type.Record.fromDescriptor(descriptor);
        final var baseAlias = Quantifier.current();
        final var baseObjectValue = QuantifiedObjectValue.of(baseAlias, baseType);

        final var indexKeyValues = ImmutableList.<Value>of(
                FieldValue.ofFieldNames(baseObjectValue, List.of("num_value_2")),
                FieldValue.ofFieldNames(baseObjectValue, List.of("num_value_2")),
                FieldValue.ofFieldNames(baseObjectValue, List.of("rec_no")));

        final var translators = ScanWithFetchMatchCandidate.computeIndexEntryToLogicalRecord(List.of(recordType),
                baseAlias, baseType, indexKeyValues, ImmutableList.of()).orElseThrow();
        final var recordValue = translators.indexEntryToRecordValue();
        assertNotNull(recordValue, "a repeated field should still yield a value based translator");

        final var entry = new IndexEntry(metaData.getIndex("dup"), Tuple.from(10L, 10L, 1L), TupleHelpers.EMPTY);
        final var byCopiers = translators.indexKeyValueToPartialRecord().toRecord(descriptor, entry);
        final var byValue = evaluate(recordValue, entry);

        assertEquals(10, byCopiers.getField(descriptor.findFieldByName("num_value_2")));
        assertSameRecord(descriptor, byCopiers, byValue);

        // The first of the two positions, as the copiers also keep.
        assertEquals("KEY:[0]", ((RecordConstructorValue)recordValue).getColumns().stream()
                .filter(column -> "num_value_2".equals(column.getField().getFieldName()))
                .findFirst().orElseThrow().getValue().toString());
    }

    @Nonnull
    private static Message evaluate(@Nonnull final Value recordValue, @Nonnull final IndexEntry entry) {
        final var typeRepository = TypeRepository.newBuilder().addTypeIfNeeded(recordValue.getResultType()).build();
        final var context = EvaluationContext.forBindingsAndTypeRepository(
                Bindings.newBuilder()
                        .set(Bindings.Internal.CORRELATION.bindingName(Quantifier.current().getId()), entry)
                        .build(),
                typeRepository);
        return (Message)recordValue.evalWithoutStore(context);
    }

    /**
     * Compares the two records field by field, descending into submessages, the two being built on different descriptors
     * and so never equal as messages.
     */
    private static void assertSameRecord(@Nonnull final Descriptors.Descriptor descriptor,
                                        @Nonnull final Message expected,
                                        @Nonnull final Message actual) {
        for (final var field : descriptor.getFields()) {
            final var actualField = actual.getDescriptorForType().findFieldByName(field.getName());
            assertNotNull(actualField, field.getFullName() + " should exist in both records");
            if (field.isRepeated()) {
                assertEquals(expected.getField(field), actual.getField(actualField), field.getFullName());
                continue;
            }
            assertEquals(expected.hasField(field), actual.hasField(actualField), field.getFullName() + " presence");
            if (!expected.hasField(field)) {
                continue;
            }
            if (field.getType() == Descriptors.FieldDescriptor.Type.MESSAGE) {
                assertSameRecord(field.getMessageType(), (Message)expected.getField(field),
                        (Message)actual.getField(actualField));
            } else {
                assertEquals(expected.getField(field), actual.getField(actualField), field.getFullName());
            }
        }
    }
}
