/*
 * RecordTypeElement.java
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.apple.foundationdb.record.query.plan.temp.view;

import com.apple.foundationdb.annotation.API;
import com.apple.foundationdb.record.query.plan.temp.AliasMap;
import com.apple.foundationdb.record.query.plan.temp.ComparisonRange;
import com.apple.foundationdb.record.query.predicates.ElementPredicate;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;

/**
 * An element representing the <em>record type</em> of each entry generated by the source.
 * @see com.apple.foundationdb.record.metadata.expressions.RecordTypeKeyExpression
 */
@API(API.Status.EXPERIMENTAL)
@SuppressWarnings("PMD.OverrideBothEqualsAndHashcode")
public class RecordTypeElement extends ElementWithSingleSource {
    public RecordTypeElement(@Nonnull Source source) {
        super(source);
    }

    @Nonnull
    @Override
    public Element withSourceMappedInto(@Nonnull Source originalSource, @Nonnull Source duplicateSource) {
        if (source.equals(duplicateSource)) {
            return new RecordTypeElement(originalSource);
        }
        return this;
    }

    @Nonnull
    @Override
    public Optional<ComparisonRange> matchWith(@Nonnull ComparisonRange existingComparisons,
                                               @Nonnull ElementPredicate predicate) {
        if (predicate.getElement().equals(this)) {
            return existingComparisons.tryToAdd(predicate.getComparison());
        }
        return Optional.empty();
    }

    @Nonnull
    @Override
    public Optional<ViewExpressionComparisons> matchSourcesWith(@Nonnull ViewExpressionComparisons viewExpressionComparisons, @Nonnull Element element) {
        return Optional.empty();
    }

    @Nullable
    @Override
    public Object eval(@Nonnull SourceEntry sourceEntry) {
        // TODO change this someday when we don't need backwards compatibility with RecordTypeKeyComparison.
        return sourceEntry.getValueFor(source);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RecordTypeElement that = (RecordTypeElement)o;
        return Objects.equals(source, that.source);
    }

    @Override
    public int semanticHashCode() {
        return Objects.hash(source);
    }

    @Override
    public int planHash(PlanHashKind hashKind) {
        return 2; // To match RecordTypeKeyExpression.planHash()
    }

    @Nonnull
    @Override
    public RecordTypeElement rebase(@Nonnull final AliasMap translationMap) {
        return new RecordTypeElement(getSource()); // TODO needs to be rebased
    }
}
