name: Run mixed mode tests for release

inputs:
  update_type:
    description: 'One of MAJOR, MINOR, BUILD, PATCH'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Base Environment
      uses: ./actions/setup-base-env
    - name: Setup FDB
      uses: ./actions/setup-fdb
    - name: Run Gradle Test
      uses: ./actions/gradle-test
      with:
        gradle_command: mixedModeTest
        gradle_args: -PreleaseBuild=false -PpublishBuild=false
    - name: Increment version
      shell: bash
      run: python build/versionutils.py gradle.properties --increment -u ${{ inputs.update_type }}
    - name: Get new version
      id: get_new_version
      shell: bash
      run: |
        echo "version=$(python build/versionutils.py gradle.properties)" >> "$GITHUB_OUTPUT"
    - name: Create markdown
      shell: bash
      run: python build/publish-mixed-mode-results.py ${{ steps.get_new_version.outputs.version }} --run-link ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > mixed-mode-results.md
    - name: Upload mixed mode results
      id: mixed_mode_results
      uses: actions/upload-pages-artifact@v3
      with:
        name: mixed-mode-results
        path: mixed-mode-results.md
    - name: Preview results
      shell: bash
      run: cat mixed-mode-results.md >> $GITHUB_STEP_SUMMARY

# TODO push results to release notes
#       - name: Checkout Main
#         run: git checkout main
#       - name: Update release notes
#         run: python build/publish-mixed-mode-results.py ${{ inputs.tag }} --release-notes docs/sphinx/source/ReleaseNotes.md --commit --run-link ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#       - name: Push release notes update
#         run: git push
