name: Run mixed mode tests for release

runs:
  using: "composite"
  steps:
    - name: Checkout sources
      uses: actions/checkout@v4.2.2
    - name: Setup Base Environment
      uses: ./actions/setup-base-env
    - name: Setup FDB
      uses: ./actions/setup-fdb
    - name: Run Gradle Test
      uses: ./actions/gradle-test
      with:
        gradle_command: mixedModeTest
        gradle_args: -PreleaseBuild=false -PpublishBuild=false
# TODO put results in step summary

# TODO push results to release notes
#       - name: Checkout Main
#         run: git checkout main
#       - name: Update release notes
#         run: python build/publish-mixed-mode-results.py ${{ inputs.tag }} --release-notes docs/sphinx/source/ReleaseNotes.md --commit --run-link ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#       - name: Push release notes update
#         run: git push
