/*
 * CascadesRuleCall.java
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.apple.foundationdb.record.query.plan.cascades;

import com.apple.foundationdb.annotation.API;
import com.apple.foundationdb.record.EvaluationContext;
import com.apple.foundationdb.record.RecordCoreArgumentException;
import com.apple.foundationdb.record.RecordCoreException;
import com.apple.foundationdb.record.query.plan.cascades.Quantifiers.AliasResolver;
import com.apple.foundationdb.record.query.plan.cascades.debug.Debugger;
import com.apple.foundationdb.record.query.plan.cascades.expressions.RelationalExpression;
import com.apple.foundationdb.record.query.plan.cascades.matching.structure.PlannerBindings;
import com.apple.foundationdb.record.query.plan.plans.RecordQueryPlan;
import com.google.common.base.Preconditions;
import com.google.common.base.Verify;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.Sets;

import javax.annotation.Nonnull;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Deque;
import java.util.Optional;
import java.util.Set;
import java.util.function.Function;

/**
 * A rule call implementation for the {@link CascadesPlanner}. This rule call implements the logic for handling new
 * expressions as they are generated by a {@link CascadesRule#onMatch(CascadesRuleCall)} and passed to the rule call
 * via the {@link #yieldExpression(Reference)} method, which consists primarily of manipulating the implicit a memo data
 * structure defined by {@link Reference}s and {@link RelationalExpression}s.
 * <br>
 * An invoked rule can in turn call {@link #yieldExpression} or {@link #yieldPartialMatch} to either declare a new resulting
 * expression or to declare a new partial match between the current expression and some candidate expression.
 *
 */
@API(API.Status.EXPERIMENTAL)
public class CascadesRuleCall implements PlannerRuleCall<Reference>, Memoizer {
    @Nonnull
    private final CascadesRule<?> rule;
    @Nonnull
    private final Reference root;
    @Nonnull
    private final Traversal traversal;
    @Nonnull
    private final Deque<CascadesPlanner.Task> taskStack;
    @Nonnull
    private final PlannerBindings bindings;
    @Nonnull
    private final PlanContext context;
    @Nonnull
    private final LinkedIdentitySet<RelationalExpression> newExpressions;
    @Nonnull
    private final LinkedIdentitySet<PartialMatch> newPartialMatches;
    @Nonnull
    private final Set<Reference> referencesWithPushedRequirements;
    @Nonnull
    private final EvaluationContext evaluationContext;

    public CascadesRuleCall(@Nonnull final PlanContext context,
                            @Nonnull final CascadesRule<?> rule,
                            @Nonnull final Reference root,
                            @Nonnull final Traversal traversal,
                            @Nonnull final Deque<CascadesPlanner.Task> taskStack,
                            @Nonnull final PlannerBindings bindings,
                            @Nonnull final EvaluationContext evaluationContext) {
        this.context = context;
        this.rule = rule;
        this.root = root;
        this.traversal = traversal;
        this.taskStack = taskStack;
        this.bindings = bindings;
        this.newExpressions = new LinkedIdentitySet<>();
        this.newPartialMatches = new LinkedIdentitySet<>();
        this.referencesWithPushedRequirements = Sets.newLinkedHashSet();
        this.evaluationContext = evaluationContext;
    }

    public void run() {
        rule.onMatch(this);
    }

    @Nonnull
    public Reference getRoot() {
        return root;
    }

    @Nonnull
    public Traversal getTraversal() {
        return traversal;
    }

    @Nonnull
    public AliasResolver newAliasResolver() {
        return new AliasResolver(traversal);
    }

    @Override
    @Nonnull
    public PlannerBindings getBindings() {
        return bindings;
    }

    /**
     * Get the planning context with metadata that might be relevant to the planner, such as the list of available
     * indexes.
     *
     * @return a {@link PlanContext} object with various metadata that could affect planning
     */
    @Nonnull
    public PlanContext getContext() {
        return context;
    }

    @Nonnull
    public <T> Optional<T> getPlannerConstraint(@Nonnull final PlannerConstraint<T> plannerConstraint) {
        if (rule.getConstraintDependencies().contains(plannerConstraint)) {
            return root.getConstraintsMap().getConstraintOptional(plannerConstraint);
        }

        throw new RecordCoreArgumentException("rule is not dependent on requested planner requirement");
    }

    @Nonnull
    public Set<Reference> getReferencesWithPushedRequirements() {
        return referencesWithPushedRequirements;
    }

    @Override
    @SuppressWarnings("PMD.CompareObjectsWithEquals") // deliberate use of == equality check for short-circuit condition
    public void yieldExpression(@Nonnull Reference expressionReference) {
        if (expressionReference == root) {
            return;
        }

        for (RelationalExpression member : expressionReference.getMembers()) {
            verifyMemoized(member);
            if (root.insertFrom(member, expressionReference)) {
                newExpressions.add(member);
                traversal.addExpression(root, member);
            }
        }
    }

    public void yieldExpression(@Nonnull Set<? extends RelationalExpression> expressions) {
        for (RelationalExpression expression : expressions) {
            yieldExpression(expression);
        }
    }

    public void yieldExpression(@Nonnull RelationalExpression expression) {
        verifyMemoized(expression);
        if (root.insert(expression)) {
            newExpressions.add(expression);
            traversal.addExpression(root, expression);
        }
    }

    private void verifyMemoized(@Nonnull RelationalExpression expression) {
        for (final var quantifier : expression.getQuantifiers()) {
            final var rangesOver = quantifier.getRangesOver();
            Verify.verify(traversal.getRefs().contains(rangesOver));
        }
    }

    /**
     * Notify the planner's data structures that a new partial match has been produced by the rule. This method may be
     * called zero or more times by the rule's <code>onMatch()</code> method.
     *
     * @param boundAliasMap the alias map of bound correlated identifiers between query and candidate
     * @param matchCandidate the match candidate
     * @param queryExpression the query expression
     * @param candidateRef the matching reference on the candidate side
     * @param matchInfo an auxiliary structure to keep additional information about the match
     */
    public void yieldPartialMatch(@Nonnull final AliasMap boundAliasMap,
                                  @Nonnull final MatchCandidate matchCandidate,
                                  @Nonnull final RelationalExpression queryExpression,
                                  @Nonnull final Reference candidateRef,
                                  @Nonnull final MatchInfo matchInfo) {
        final PartialMatch newPartialMatch =
                new PartialMatch(boundAliasMap,
                        matchCandidate,
                        root,
                        queryExpression,
                        candidateRef,
                        matchInfo);
        root.addPartialMatchForCandidate(matchCandidate, newPartialMatch);
        newPartialMatches.add(newPartialMatch);
    }

    @SuppressWarnings({"PMD.CompareObjectsWithEquals"}) // deliberate use of id equality check for short-circuit condition
    public <T> void pushConstraint(@Nonnull final Reference reference,
                                   @Nonnull final PlannerConstraint<T> plannerConstraint,
                                   @Nonnull final T requirement) {
        Verify.verify(root != reference);
        final ConstraintsMap requirementsMap = reference.getConstraintsMap();
        if (requirementsMap.pushProperty(plannerConstraint, requirement).isPresent()) {
            referencesWithPushedRequirements.add(reference);
        }
    }

    @Nonnull
    public Collection<RelationalExpression> getNewExpressions() {
        return Collections.unmodifiableCollection(newExpressions);
    }

    @Nonnull
    public Set<PartialMatch> getNewPartialMatches() {
        return newPartialMatches;
    }

    @Nonnull
    public EvaluationContext getEvaluationContext() {
        return evaluationContext;
    }

    @Nonnull
    @Override
    @SuppressWarnings("PMD.CompareObjectsWithEquals")
    public Reference memoizeExpression(@Nonnull final RelationalExpression expression) {
        if (expression.getQuantifiers().isEmpty()) {
            return memoizeLeafExpression(expression);
        }

        Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.BEGIN)));
        try {
            Preconditions.checkArgument(!(expression instanceof RecordQueryPlan));

            final var referencePathsList =
                    expression.getQuantifiers()
                            .stream()
                            .map(Quantifier::getRangesOver)
                            .map(traversal::getParentRefPaths)
                            .collect(ImmutableList.toImmutableList());

            final var expressionToReferenceMap = new LinkedIdentityMap<RelationalExpression, Reference>();
            referencePathsList.stream()
                    .flatMap(Collection::stream)
                    .forEach(referencePath -> {
                        final var referencingExpression = referencePath.getExpression();
                        if (expressionToReferenceMap.containsKey(referencingExpression)) {
                            if (expressionToReferenceMap.get(referencingExpression) != referencePath.getReference()) {
                                throw new RecordCoreException("expression used in multiple references");
                            }
                        } else {
                            expressionToReferenceMap.put(referencePath.getExpression(), referencePath.getReference());
                        }
                    });

            final var referencingExpressions =
                    referencePathsList.stream()
                            .map(referencePaths -> referencePaths.stream().map(Traversal.ReferencePath::getExpression).collect(LinkedIdentitySet.toLinkedIdentitySet()))
                            .collect(ImmutableList.toImmutableList());

            final var referencingExpressionsIterator = referencingExpressions.iterator();
            final var commonReferencingExpressions = new LinkedIdentitySet<>(referencingExpressionsIterator.next());
            while (referencingExpressionsIterator.hasNext()) {
                commonReferencingExpressions.retainAll(referencingExpressionsIterator.next());
            }

            for (final var commonReferencingExpression : commonReferencingExpressions) {
                if (Reference.isMemoizedExpression(commonReferencingExpression, expression)) {
                    Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.REUSED)));
                    final var reference = expressionToReferenceMap.get(commonReferencingExpression);
                    Verify.verifyNotNull(reference);
                    Verify.verify(reference != this.root);
                    return reference;
                }
            }
            Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.NEW)));
            final var newRef = Reference.of(expression);
            traversal.addExpression(newRef, expression);
            return newRef;
        } finally {
            Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.END)));
        }
    }

    @Nonnull
    @Override
    public Reference memoizeLeafExpression(@Nonnull final RelationalExpression expression) {
        Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.BEGIN)));
        try {
            Preconditions.checkArgument(!(expression instanceof RecordQueryPlan));
            Preconditions.checkArgument(expression.getQuantifiers().isEmpty());

            final var leafRefs = traversal.getLeafReferences();

            for (final var leafRef : leafRefs) {
                for (final var member : leafRef.getMembers()) {
                    if (Reference.isMemoizedExpression(expression, member)) {
                        Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.REUSED)));
                        return leafRef;
                    }
                }
            }
            Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.NEW)));
            final var newRef = Reference.of(expression);
            traversal.addExpression(newRef, expression);
            return newRef;
        } finally {
            Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.END)));
        }
    }

    @Nonnull
    @Override
    public Reference memoizeMemberPlans(@Nonnull Reference reference,
                                        @Nonnull final Collection<? extends RecordQueryPlan> plans) {
        return memoizeExpressionsExactly(plans, reference::referenceFromMembers);
    }

    @Nonnull
    @Override
    public Reference memoizePlans(@Nonnull RecordQueryPlan... plans) {
        return memoizePlans(Arrays.asList(plans));
    }

    @Nonnull
    @Override
    public Reference memoizePlans(@Nonnull final Collection<? extends RecordQueryPlan> plans) {
        return memoizeExpressionsExactly(plans, Reference::from);
    }

    @Nonnull
    @Override
    public Reference memoizeReference(@Nonnull final Reference reference) {
        return memoizeExpressionsExactly(reference.getMembers(), members -> reference);
    }

    @Nonnull
    private Reference memoizeExpressionsExactly(@Nonnull final Collection<? extends RelationalExpression> expressions,
                                                @Nonnull Function<Set<? extends RelationalExpression>, Reference> referenceCreator) {
        Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.BEGIN)));
        try {
            final var expressionSet = new LinkedIdentitySet<>(expressions);

            //
            // Note that we cannot ever reuse a reference containing just plans unless we can somehow prove
            // that the reference cannot subsequently be pruned. Currently, we cannot prove that.
            // TODO Check if we can reuse a reference if at least one expression is not a plan as that reference
            //      is only pruned at the very last OptimizeGroup of the root. I will leave the disabled code here
            //      for now. https://github.com/FoundationDB/fdb-record-layer/issues/2766
            //
            //noinspection PointlessBooleanExpression
            if (false && expressionSet.size() == 1) {
                final Optional<Reference> memoizedRefMaybe = findExpressionsInMemo(expressionSet);
                if (memoizedRefMaybe.isPresent()) {
                    Debugger.withDebugger(debugger ->
                            expressionSet.forEach(plan -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.REUSED))));
                    return memoizedRefMaybe.get();
                }
            }

            final var newRef = referenceCreator.apply(expressionSet);
            for (final var plan : expressionSet) {
                Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.NEW)));
                traversal.addExpression(newRef, plan);
            }
            return newRef;
        } finally {
            Debugger.withDebugger(debugger -> debugger.onEvent(new Debugger.InsertIntoMemoEvent(Debugger.Location.END)));
        }
    }

    @Nonnull
    private Optional<Reference> findExpressionsInMemo(final LinkedIdentitySet<? extends RelationalExpression> planSet) {
        final var planIterator = planSet.iterator();
        Verify.verify(planIterator.hasNext());
        final var refsContainingAllPlans = new LinkedIdentitySet<>(traversal.getRefsContaining(planIterator.next()));
        while (planIterator.hasNext()) {
            final var currentRefsContainingPlan = traversal.getRefsContaining(planIterator.next());
            refsContainingAllPlans.retainAll(currentRefsContainingPlan);
        }

        //
        // There should only at most be one exact match which is the ref that contains exactly all plans and nothing else.
        //
        return refsContainingAllPlans.stream()
                .filter(refContainingAllPlans -> refContainingAllPlans.getMembers().size() == planSet.size())
                .findFirst();
    }

    @Nonnull
    @Override
    public ReferenceBuilder memoizeExpressionBuilder(@Nonnull final RelationalExpression expression) {
        return new ReferenceBuilder() {
            @Nonnull
            @Override
            public Reference reference() {
                return memoizeExpression(expression);
            }

            @Nonnull
            @Override
            public Set<? extends RelationalExpression> members() {
                return LinkedIdentitySet.of(expression);
            }
        };
    }

    @Nonnull
    @Override
    public ReferenceBuilder memoizeMemberPlansBuilder(@Nonnull Reference reference,
                                                      @Nonnull final Collection<? extends RecordQueryPlan> plans) {
        return memoizeExpressionsBuilder(plans, reference::referenceFromMembers);
    }

    @Nonnull
    @Override
    public ReferenceBuilder memoizePlansBuilder(@Nonnull RecordQueryPlan... plans) {
        return memoizePlansBuilder(Arrays.asList(plans));
    }

    @Nonnull
    @Override
    public ReferenceBuilder memoizePlansBuilder(@Nonnull final Collection<? extends RecordQueryPlan> plans) {
        return memoizeExpressionsBuilder(plans, Reference::from);
    }

    @Nonnull
    private ReferenceBuilder memoizeExpressionsBuilder(@Nonnull final Collection<? extends RelationalExpression> expressions,
                                                       @Nonnull Function<Set<? extends RelationalExpression>, Reference> refAction) {
        final var expressionSet = new LinkedIdentitySet<>(expressions);
        return new ReferenceBuilder() {
            @Nonnull
            @Override
            public Reference reference() {
                return memoizeExpressionsExactly(expressions, refAction);
            }

            @Nonnull
            @Override
            public Set<? extends RelationalExpression> members() {
                return expressionSet;
            }
        };
    }

    public void emitEvent(@Nonnull Debugger.Location location) {
        Debugger.withDebugger(debugger ->
                debugger.onEvent(
                        new Debugger.TransformRuleCallEvent(root, taskStack, location, root,
                                bindings.get(rule.getMatcher()), rule, this)));
    }
}
