/*
 * Column.java
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2015-2022 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.apple.foundationdb.record.query.plan.cascades;

import com.apple.foundationdb.record.PlanHashable;
import com.apple.foundationdb.record.PlanSerializable;
import com.apple.foundationdb.record.PlanSerializationContext;
import com.apple.foundationdb.record.planprotos.PRecordConstructorValue.PColumn;
import com.apple.foundationdb.record.query.plan.cascades.typing.Type.Record.Field;
import com.apple.foundationdb.record.query.plan.cascades.values.Value;

import javax.annotation.Nonnull;
import java.util.Objects;
import java.util.Optional;

/**
 * A class to hold a value computing a column together with information about the field of a record it supplies
 * the result for.
 * @param <V> type parameter for the {@link Value}
 */
public class Column<V extends Value> implements PlanHashable, PlanSerializable {
    @Nonnull
    private final Field field;
    @Nonnull
    private final V value;

    public Column(@Nonnull final Field field, @Nonnull final V value) {
        this.field = field;
        this.value = value;
    }

    @Nonnull
    public Field getField() {
        return field;
    }

    @Nonnull
    public V getValue() {
        return value;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Column)) {
            return false;
        }
        final Column<?> column = (Column<?>)o;
        return getField().equals(column.getField()) && getValue().equals(column.getValue());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getField(), getValue());
    }

    public static <V extends Value> Column<V> unnamedOf(@Nonnull final V value) {
        return new Column<>(Field.unnamedOf(value.getResultType()), value);
    }

    public static <V extends Value> Column<V> of(@Nonnull Optional<String> fieldNameOptional, @Nonnull final V value) {
        return new Column<>(Field.of(value.getResultType(), fieldNameOptional), value);
    }

    public static <V extends Value> Column<V> of(@Nonnull final Field field, @Nonnull final V value) {
        return new Column<>(field, value);
    }

    @Override
    public int planHash(@Nonnull final PlanHashMode hashMode) {
        // plan hash everything substantial except the field result type
        // TODO: we should revisit normalization of field names and how they contribute the this hash calculation.
        final var fieldNameOptional = getField().getFieldNameOptional();
        if (fieldNameOptional.isPresent() && !Field.isAutoGenerated(fieldNameOptional.get())) {
            return PlanHashable.objectsPlanHash(hashMode, getField().getFieldIndexOptional(), fieldNameOptional.get(), getValue());
        } else {
            return PlanHashable.objectsPlanHash(hashMode, getField().getFieldIndexOptional(), getValue());
        }
    }

    @Nonnull
    @Override
    public PColumn toProto(@Nonnull final PlanSerializationContext serializationContext) {
        return PColumn.newBuilder()
                .setField(field.toProto(serializationContext))
                .setValue(value.toValueProto(serializationContext))
                .build();
    }

    @Nonnull
    public static Column<? extends Value> fromProto(@Nonnull final PlanSerializationContext serializationContext,
                                                    @Nonnull final PColumn columnProto) {
        return new Column<>(Field.fromProto(serializationContext, Objects.requireNonNull(columnProto.getField())),
                Value.fromValueProto(serializationContext, Objects.requireNonNull(columnProto.getValue())));
    }

}
