name: Setup Base Environment

outputs:
  python-version:
    value: ${{ steps.setup-python.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
