name: Run standard tests for release


runs:
  using: "composite"
  steps:
    - name: Setup Base Environment
      id: setup-base
      uses: ./actions/setup-base-env
    - name: Setup FDB
      uses: ./actions/setup-fdb
    - name: Run Gradle Test
      uses: ./actions/gradle-test
      with:
        gradle_args: -PreleaseBuild=true -PpublishBuild=true

