name: Setup FDB

inputs:
  fdb_version:
    description: 'Version of FDB to run'
    required: false
    default: "7.3.42"

runs:
  using: "composite"
  steps:
    - name: Set FDB Filenames
      id: fdb_filenames
      shell: bash
      run: |
        echo "client_deb=foundationdb-clients_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
        echo "server_deb=foundationdb-server_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
    - name: Check FDB Binaries Cache
      id: cache_fdb
      uses: actions/cache@v3
      with:
        path: ~/.fdb-cache
        key: ${{ runner.os }}-fdb-debs-${{ inputs.fdb_version }}
    - name: Download FDB Binaries
      if: steps.cache_fdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.fdb-cache
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.client_deb }}
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: Install FDB Server
      shell: bash
      run: sudo dpkg -i ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: Fix FDB Network Addresses
      shell: bash
      run: sudo sed -i -e "s/public_address = auto:\$ID/public_address = 127.0.0.1:\$ID/g" -e "s/listen_address = public/listen_address = 0.0.0.0:\$ID/g" /etc/foundationdb/foundationdb.conf
    - name: Start FDB Server
      shell: bash
      run: sudo /usr/lib/foundationdb/fdbmonitor /etc/foundationdb/foundationdb.conf --daemonize
    - name: Switch FDB to SSD
      shell: bash
      run: fdbcli --exec "configure single ssd storage_migration_type=aggressive; status"
