name: Setup FDB

inputs:
  fdb_version:
    description: 'Version of FDB to run'
    required: false
    default: "7.3.42"

runs:
  using: "composite"
  steps:
    - name: Set FDB Filenames
      id: fdb_filenames
      shell: bash
      run: |
        echo "client_deb=foundationdb-clients_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
        echo "server_deb=foundationdb-server_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
    - name: Check FDB Binaries Cache
      id: cache_fdb
      uses: actions/cache@v3
      with:
        path: ~/.fdb-cache
        key: ${{ runner.os }}-fdb-debs-${{ inputs.fdb_version }}
    - name: Download FDB Binaries
      if: steps.cache_fdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.fdb-cache
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.client_deb }}
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: Install FDB Server
      shell: bash
      run: sudo dpkg -i ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: debugging
      shell: bash
      run: fdbcli -C /etc/foundationdb/fdb.cluster --exec "status details" --log
    - name: Stop default fdb
      shell: bash
      run: sudo service foundationdb stop
    - name: debugging
      shell: bash
      run: sudo ps -u foundationdb || echo "None"

    - name: Experiment
      shell: bash
      run: >-
        sudo sed -i -e "s/:4500/:4800/g"
        /etc/foundationdb/fdb.cluster
    - name: Experiment
      shell: bash
      run: >-
        sudo sed -i -e "s/fdbserver.4500/fdbserver.4800/g"
        /etc/foundationdb/foundationdb.conf

    - name: debugging
      shell: bash
      run: sudo ls -lh /var/lib/foundationdb
    - name: debugging
      shell: bash
      run: sudo ls -lh /var/lib/foundationdb/data
    - name: debugging
      shell: bash
      run: ls -lh /etc/foundationdb
    - name: debugging
      shell: bash
      run: sudo netstat -nlp
#     - name: experiment -- I don't know how to daemonize this
#       shell: bash
#       run: sudo -u foundationdb /usr/sbin/fdbserver -p 127.0.0.1:4800 -C /etc/foundationdb/fdb.cluster -d /var/lib/foundationdb/data/4800 -L /var/log/foundationdb/ --machine-id 23948792384080c
    - name: debugging
      shell: bash
      run: sudo /usr/lib/foundationdb/fdbmonitor --conffile /etc/foundationdb/foundationdb.conf --lockfile /var/run/fdbmonitor.pid --loggroup fdbX & fdbcli -C /etc/foundationdb/fdb.cluster --exec "status details" --log # --daemonize

    - name: debugging
      shell: bash
      run: fdbcli -C /etc/foundationdb/fdb.cluster --exec "status details" --log
    - name: debugging
      shell: bash
      run: sudo ps -u foundationdb
    - name: debugging
      shell: bash
      run: sudo netstat -nlp
    - name: debugging
      shell: bash
      run: sudo cat /etc/foundationdb/foundationdb.conf
    - name: debugging
      shell: bash
      run: sudo ls -lh /var/lib/foundationdb/data
    - name: debugging
      shell: bash
      run: sudo ls -lh /var/lib/foundationdb/data/4500
    - name: debugging
      shell: bash
      run: sudo ls -lh /var/lib/foundationdb/data/4800
    - name: debugging
      shell: bash
      run: tail -n +1 trace.*.xml
    - name: debugging
      shell: bash
      run: sudo bash -c "tail -n +1 /var/log/foundationdb/*"
    - name: debugging
      shell: bash
      run: exit(7)
    - name: Create fdb-environment.yaml
      shell: bash
      run: |
        echo "clusterFiles: " >> fdb-environment.yaml
        echo "  - /etc/foundationdb/fdb1.cluster" >> fdb-environment.yaml
        echo "  - /etc/foundationdb/fdb2.cluster" >> fdb-environment.yaml


# 2025-09-17T20:25:56.6537954Z <Event Severity="10" Time="1758140723.199576" DateTime="2025-09-17T20:25:23Z"
# Type="ProgramStart"
# ID="0000000000000000"
# RandomSeed="220297604"
# SourceVersion="97eb76a3faf60b6da333f8136ccc371986d66aa0"
# Version="7.3.42"
# PackageName="7.3"
# FileSystem=""
# DataFolder="/var/lib/foundationdb/data/4800"
# WorkingDirectory="/"
# ClusterFile="file:///etc/foundationdb/fdb.cluster"
# ConnectionString="hjxVNCVQ:UuvgBhXC@127.0.0.1:4800"
# ActualTime="1758140723"
# EnvironmentKnobOptions="none"
# CommandLine="/usr/sbin/fdbserver
#    --cluster-file=/etc/foundationdb/fdb.cluster
#    --datadir=/var/lib/foundationdb/data/4800
#    --listen-address=public
#    --logdir=/var/log/foundationdb
#    --public-address=auto:4800"
# BuggifyEnabled="0"
# FaultInjectionEnabled="1"
# MemoryLimit="8589934592"
# VirtualMemoryLimit="0"
# ProtocolVersion="0x0FDB00B073000000"
# ThreadID="9889572679649731099"
# Machine="127.0.0.1:4800"
# LogGroup="default"
# TrackLatestType="Original" />


# 2025-09-17T20:25:56.5133346Z <Event Severity="10" Time="1758140718.612520" DateTime="2025-09-17T20:25:18Z"
# Type="ProgramStart"
# ID="0000000000000000"
# RandomSeed="3591645195"
# SourceVersion="97eb76a3faf60b6da333f8136ccc371986d66aa0"
# Version="7.3.42"
# PackageName="7.3"
# FileSystem=""
# DataFolder="/var/lib/foundationdb/data/4500"
# WorkingDirectory="/"
# ClusterFile="file:///etc/foundationdb/fdb.cluster"
# ConnectionString="hjxVNCVQ:UuvgBhXC@127.0.0.1:4500"
# ActualTime="1758140718"
# EnvironmentKnobOptions="none"
# CommandLine="/usr/sbin/fdbserver
#   --cluster-file=/etc/foundationdb/fdb.cluster
#   --datadir=/var/lib/foundationdb/data/4500
#   --listen-address=public
#   --logdir=/var/log/foundationdb
#   --public-address=auto:4500"
# BuggifyEnabled="0"
# FaultInjectionEnabled="1"
# MemoryLimit="8589934592"
# VirtualMemoryLimit="0"
# ProtocolVersion="0x0FDB00B073000000"
# ThreadID="2383862468738596229"
# Machine="127.0.0.1:4500"
# LogGroup="default"
# TrackLatestType="Original" />
