name: Setup FDB

inputs:
  fdb_version:
    description: 'Version of FDB to run'
    required: false
    default: "7.3.42"

runs:
  using: "composite"
  steps:
    - name: Set FDB Filenames
      id: fdb_filenames
      shell: bash
      run: |
        echo "client_deb=foundationdb-clients_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
        echo "server_deb=foundationdb-server_${{ inputs.fdb_version }}-1_amd64.deb" >> "${GITHUB_OUTPUT}"
    - name: Check FDB Binaries Cache
      id: cache_fdb
      uses: actions/cache@v3
      with:
        path: ~/.fdb-cache
        key: ${{ runner.os }}-fdb-debs-${{ inputs.fdb_version }}
    - name: Download FDB Binaries
      if: steps.cache_fdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.fdb-cache
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.client_deb }}
        wget -O ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }} -nv https://github.com/apple/foundationdb/releases/download/${{ inputs.fdb_version }}/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: Install FDB Server
      shell: bash
      run: sudo dpkg -i ~/.fdb-cache/${{ steps.fdb_filenames.outputs.client_deb }} ~/.fdb-cache/${{ steps.fdb_filenames.outputs.server_deb }}
    - name: Fix FDB Network Addresses
      shell: bash
      run: sudo sed -i -e "s/public_address = auto:\$ID/public_address = 127.0.0.1:\$ID/g" -e "s/listen_address = public/listen_address = 0.0.0.0:\$ID/g" /etc/foundationdb/foundationdb.conf
    # Setup 2 cluster conf files
    - name: Create cluster1 config file
      shell: bash
      run: sudo cp /etc/foundationdb/foundationdb.conf /etc/foundationdb/foundationdb1.conf
    - name: Create cluster2 config file
      shell: bash
      run: sudo cp /etc/foundationdb/foundationdb.conf /etc/foundationdb/foundationdb2.conf
    - name: Update cluster1 config file
      shell: bash
      run: >-
        sudo sed -i -e "s/\/etc\/foundationdb\/fdb.cluster/\/etc\/foundationdb\/fdb1.cluster/g"
                    -e "s/\/var\/log\/foundationdb/\/var\/log\/foundationdb1/"
                 /etc/foundationdb/foundationdb1.conf
    - name: Update cluster2 config file
      shell: bash
      run: >-
        sudo sed -i -e "s/\/etc\/foundationdb\/fdb.cluster/\/etc\/foundationdb\/fdb2.cluster/g"
                    -e "s/\/var\/log\/foundationdb/\/var\/log\/foundationdb2/"
                    -e "s/fdbserver.4500/fdbserver.4600/g"
                 /etc/foundationdb/foundationdb2.conf
    - name: debugging
      shell: bash
      run: cat /etc/foundationdb/foundationdb1.conf
    - name: debugging
      shell: bash
      run: cat /etc/foundationdb/foundationdb2.conf
    # Setup two cluster files for the two configs
    - name: Create cluster1 clusterfile
      shell: bash
      run: sudo bash -c "echo 'fdb1:$(mktemp -u XXXXXXXX)@127.0.0.1:4500' > /etc/foundationdb/fdb1.cluster"
    - name: Create cluster2 clusterfile
      shell: bash
      run: sudo bash -c "echo 'fdb2:$(mktemp -u XXXXXXXX)@127.0.0.1:4600' > /etc/foundationdb/fdb2.cluster"
    - name: Set clusterfile permissions
      shell: bash
      run: sudo chown foundationdb:foundationdb /etc/foundationdb/fdb1.cluster /etc/foundationdb/fdb2.cluster
    - name: Set clusterfile permissions
      shell: bash
      run: sudo chmod 664 /etc/foundationdb/fdb1.cluster /etc/foundationdb/fdb2.cluster


    - name: Remove default cluster file / config
      shell: bash
      run: sudo rm /etc/foundationdb/fdb.cluster /etc/foundationdb/foundationdb.conf
    - name: Stop default fdb
      shell: bash
      run: sudo killall fdbmonitor
    - name: Cleanup default logs
      shell: bash
      run: sudo bash -c "rm /var/log/foundationdb/trace.*"
  

    - name: debugging
      shell: bash
      run: ps
    - name: debugging
      shell: bash
      run: ls -lh /etc/foundationdb
    # Start the two servers
    - name: Start FDB Server 1
      shell: bash
      run: sudo /usr/lib/foundationdb/fdbmonitor --help
    - name: Start FDB Server 1
      shell: bash
      run: sudo /usr/lib/foundationdb/fdbmonitor --conffile /etc/foundationdb/foundationdb1.conf --lockfile /var/run/fdbmonitor1.pid --loggroup fdb1 --daemonize
#     - name: Start FDB Server 2
#       shell: bash
#       run: sudo /usr/lib/foundationdb/fdbmonitor --conffile /etc/foundationdb/foundationdb2.conf --lockfile /var/run/fdbmonitor2.pid --loggroup fdb2 --daemonize
    - name: debugging
      shell: bash
      run: sudo ls -lh /var/log/foundationdb
    - name: debugging
      shell: bash
      run: sudo bash -c "head /var/log/foundationdb/trace.*"
    - name: debugging
      shell: bash
      run: sudo bash -c "tail /var/log/foundationdb/trace.*"
    - name: Switch FDB 1 to SSD
      shell: bash
      run: fdbcli -C /etc/foundationdb/fdb1.cluster --exec "configure single ssd storage_migration_type=aggressive; status"
    - name: Switch FDB 2 to SSD
      shell: bash
      run: fdbcli -C /etc/foundationdb/fdb2.cluster --exec "configure single ssd storage_migration_type=aggressive; status"
    - name: Create fdb-environment.yaml
      shell: bash
      run: |
        echo "clusterFiles: " >> fdb-environment.yaml
        echo "  - /etc/foundationdb/fdb1.cluster" >> fdb-environment.yaml
        echo "  - /etc/foundationdb/fdb2.cluster" >> fdb-environment.yaml
