name: Patch Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build off of'
        required: true


jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      packages: write
      pages: read
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Base Environment
        uses: ./actions/setup-base-env
      - name: Setup FDB
        uses: ./actions/setup-fdb
      - name: Configure Git
        run: |
          git config --global user.name 'FoundationDB CI'
          git config --global user.email 'foundationdb_ci@apple.com'

      - name: Build and publish release
        uses: ./actions/release-build-publish
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          update_type: PATCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
